### ISSUE TITLE
TypeError: must be real number, not NoneType on cadrl

### ISSUE THREAD

**Issue by takato86** [tessavdheiden/SCR#2]
Hi. Thanks for your great works.
I got an error when I ran your program.

My environment is
```
Ubuntu 18.0.4
python==3.7.9
pyrvo2==0.0.0
gym==0.18.0
GitPython==3.1.12
pandas==1.2.0
numpy==1.19.5
```

```
python train.py --policy=cadrl --output_dir=data/output/cadrl
```
After that, I got the following. 
```
Traceback (most recent call last):
  File "train.py", line 185, in <module>
    main()
  File "train.py", line 135, in main
    explorer.run_k_episodes(il_episodes, 'train', update_memory=True, imitation_learning=True)
  File "/SCR/crowd_nav/utils/explorer.py", line 109, in run_k_episodes
    action = self.robot.act(ob)
  File "/SCR/crowd_sim/envs/utils/robot.py", line 13, in act
    action = self.policy.predict(state)
  File "/SCR/crowd_sim/envs/policy/orca.py", line 106, in predict
    self.max_speed, human_state.velocity)
  File "src/rvo2.pyx", line 97, in rvo2.PyRVOSimulator.addAgent
TypeError: must be real number, not NoneType
```

It seems that the observation includes None Type depending on the param "multiagent_training" as false.
Please tell me how to run your program successfully.
Sorry for my unfamiliar English.

**Comment by saaangooooo** [comment]
Maybe you should just do it without the "="?
```
python train.py --policy cadrl --output_dir data/output/cadrl
```
